# Generated by Django 3.1.7 on 2021-03-09 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('length', models.DurationField(default=datetime.timedelta(0))),
                ('video_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
