# Generated by Django 3.1.7 on 2021-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
