# Generated by Django 3.1.7 on 2021-03-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='visible',
            new_name='approved',
        ),
    ]
