# Generated by Django 3.1.7 on 2021-03-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('videos_available', models.BooleanField(default=False)),
                ('unlimited_training_and_meal_plans', models.BooleanField(default=False)),
                ('chat_support', models.BooleanField(default=False)),
                ('shop_discount', models.BooleanField(default=False)),
                ('plan_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
