# Generated by Django 3.1.7 on 2021-03-15 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
                ('monthly_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('videos_available', models.BooleanField(default=False)),
                ('unlimited_training_and_meal_plans', models.BooleanField(default=False)),
                ('chat_support', models.BooleanField(default=False)),
                ('shop_discount', models.BooleanField(default=False)),
                ('plan_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(editable=False, max_length=32)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('full_name', models.CharField(max_length=60)),
                ('email_address', models.CharField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(max_length=80)),
                ('address_line2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=50)),
                ('county_or_region', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('package_in_cart', models.TextField(default='')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='members.member')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe.package')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('monthly_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.package')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_count', to='subscribe.subscription')),
            ],
        ),
    ]
