# Generated by Django 3.1.7 on 2021-03-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='chat_support',
            new_name='all_videos_available',
        ),
    ]
