# Generated by Django 3.1.7 on 2021-03-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscription_cardholder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
