# Generated by Django 3.1.7 on 2021-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_remove_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='package',
        ),
        migrations.AlterField(
            model_name='subscriptioncount',
            name='quantity',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
