# Generated by Django 3.1.7 on 2021-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20210326_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
