# Generated by Django 3.1.7 on 2021-03-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210324_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Requests'},
        ),
    ]
