# Generated by Django 3.1.7 on 2021-03-24 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210324_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 24, 19, 30, 45, 410742, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
