# Generated by Django 3.1.7 on 2021-03-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='quanitty',
            new_name='quantity',
        ),
    ]
