# Generated by Django 3.1.7 on 2021-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(default=models.CharField(max_length=254), max_length=254),
        ),
    ]
