# Generated by Django 3.1.7 on 2021-03-08 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_product_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourite',
        ),
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
