# Generated by Django 3.1.7 on 2021-03-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='vip_discount_percentage',
            field=models.IntegerField(default=50),
        ),
    ]
