# Generated by Django 3.1.7 on 2021-03-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210313_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourite',
        ),
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
