# Generated by Django 3.1.7 on 2021-03-15 23:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_email_address', models.CharField(blank=True, max_length=254, null=True)),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_address_line1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_address_line2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=50, null=True)),
                ('default_county_or_region', models.CharField(blank=True, max_length=50, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
    ]
