# Generated by Django 3.1.7 on 2021-03-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210326_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
