# Generated by Django 3.1.7 on 2021-03-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210306_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
