# Generated by Django 3.1.7 on 2021-03-07 15:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_default_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
