# Generated by Django 3.1.7 on 2021-03-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
